chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.ChatView.as_view(), name='chat_index'),
    path('<pk>', views.ChatDirectView.as_view(), name='chat_direct'),
    path('send/<pk>/', views.SendChat.as_view(), name='send_chat'),
    path('receive/<pk>/', views.ReceiveChat.as_view(), name='receive_chat'),
    path('notification/', views.ChatNotif.as_view(), name='notif_chat'),
]

post/urls.py
from django.urls import path
from post.views import views
from post.views import jsonview

app_name = 'post'
urlpatterns = [
    path('', views.PostListView.as_view(), name='posts'),
    path('post/<pk>/', views.PostDetailView.as_view(), name='detail'),
    # path('like/', views.LikeView.as_view(), name='like_post'),
    path('create/', views.PostCreate.as_view(), name='create_post'),
    path('create_comment/', views.CommentCreate.as_view(), name='create_comment'),
    path('post/<pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
    path('post/<pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('comment/<pk>/delete/', views.CommentDeleteView.as_view(), name='comm_delete'),
    path('comment/<pk>/update/', views.CommentUpdateView.as_view(), name='comm_update'),
    path('spin', views.Post_json.as_view(), name='post_spin'),
    
    #=========================JSON=====================================
    
    path('comment/<pk>', jsonview.CommentJson.as_view(), name='comment_json'),
    path('post_json', jsonview.post_json, name='post_json'),
    path('post/<pk>/like/', jsonview.LikeView.as_view(), name='like_post'),
]

src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('sessions/', include('user_sessions.urls', namespace='user_sessions')),
    path('user/', include('user.urls', namespace='user')),
    path('', include('post.urls', namespace='post')),
    path('chat/', include('chat.urls', namespace='chat')),

    path('auth/reset_password/', auth_views.PasswordResetView.as_view(
        template_name='user/password_reset_form.html'), name='password_reset'),
    
    path('auth/reset_password_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'), name='password_reset_done'),
    
    path('auth/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html'), name='password_reset_confirm'),
    
    path('auth/reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/password_reset_complete.html'), name='password_reset_complete'),

    path('auth/change_password/', auth_views.PasswordChangeView.as_view(
        template_name='user/change-password.html'), name='password_change'),

    path('user-api/', include('user.api.urls', namespace='user_api')),

    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('auth/register/', views.RegisterView.as_view(), name='register'),
    path('auth/login/', views.LoginView.as_view(), name='login'),
    path('auth/logout/', views.LogoutView.as_view(), name='logout'),

    path('<pk>/', views.UserDetailView.as_view(), name='profile'),
    path('follow/<pk>', views.FollowView.as_view(), name='follow'),
    path('<pk>/update/', views.UserUpdateView.as_view(), name='update'),
    path('<pk>/following/', views.FollowingView.as_view(), name='following'),
]

templates/main/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sociama {% block title %}{% endblock title %}</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesomefree/css/all.min.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css.map' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.min.css' %}">  
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/chat.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/post.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/user.css' %}">
    <!-- Jasminn Admin -->
    <script src="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/js/adminlte.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/css/adminlte.min.css">
</head>
<body>
    {% include "main/nav.html" %}
    {% block body %}
    {% endblock %}

    {% comment %} <button id="back-to-top-btn"><i class="fas fa-chevron-up btn-arrow"></i></button> {% endcomment %}

    <!-- Script -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'main/main.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/infinite.min.js' %}"></script>
</body>
</html>

templates/main/ex.html
<form action="" method="POST" id="likeform" name="post_pk">
    {% csrf_token %}
    <input type="hidden" name="post_pk" value="{{post.id}}">
    
    <div class="d-flex justify-content-start socials p-1">
        
        <button class="btn" type="submit" id="likeBtn">
            {% if request.user not in post.post_likes.all %}
                <i id="postLike" class="far fa-heart" name="like_id" style="color: rgb(5, 92, 163);font-size: 18px;" value="unliked"></i>
            {% else %}
                <i id="postLike" class="fa fa-heart" name="like_id" style="color: red;font-size: 18px;" value="liked"></i> 
            {% endif %}
            <span class="">{{post.likes_no}}</span>
        </button>
        
        <a class="btn" href="{% url 'post:detail' post.pk %}">
            <i class="fas fa-comments mx-1"></i><span>{{post.comment_no}}</span>
        </a>
    </div>
</form>


{% comment %} {% for post in posts %}
    {% for img in post.post_images.all %}
        <div class="col-md-4">
            <figure>
                <img class="img-fluid" src="{{ img.image.url }}" alt="" style="height: 90px; width:70px;">
            </figure>
        </div>
    {% endfor %}
{% endfor %} {% endcomment %}

templates/main/nav.html
{% load static %}
{% load widget_tweaks %}
<!-- Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid justify-content-between">
        <!-- Left elements -->
        <div class="d-flex">
            <!-- Brand -->
            <a class="navbar-brand me-2 mb-1 d-flex align-items-center" href="{% url 'post:posts' %}">
                <img src="{% static 'images/logo.png' %}" height="25" alt="Sociama Logo" loading="lazy" style="margin-top: 2px;" />
            </a>

            <!-- Search form -->
            <form class="input-group w-auto my-auto d-none d-sm-flex">
                <input autocomplete="off" type="search" class="form-control rounded" placeholder="Search" style="min-width: 125px;" />
                <span class="input-group-text border-0 d-none d-lg-flex"><i class="fas fa-search"></i></span>
            </form>
        </div>
        <!-- Left elements -->

        <!-- Right elements -->
        <ul class="navbar-nav flex-row">
            <li class="nav-item me-3 me-lg-1">
                {% if request.user.is_authenticated %}
                    <div class="dropdown nav-user">
                        <img class="dropdown-toggle mt-1 nav-user-image" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{ request.user.profile_pic.url }}" alt="">
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="{% url 'user:profile' request.user %}">{{request.user|capfirst}}</a>
                                <a class="dropdown-item" href="">Settings</a>
                                <a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a>
                        </div>
                    </div>
                {% else %}
                    <a class="btn btn-secondary" href="{% url 'user:login' %}">Login</a>
                {% endif %}
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item me-3 me-lg-1">
                    <a class="nav-link chat" href="{% url 'post:create_post' %}">
                        <span><i class="fas fa-plus-circle fa-lg"></i> Post</span>
                    </a>
                </li>
                <li class="nav-item me-3 me-lg-1">
                    <a class="nav-link" href="{% url 'chat:chat_index' %}">
                        <span><i class="fas fa-users fa-lg"></i></span>
                    </a>
                </li>
                <li class="nav-item dropdown me-3 me-lg-1">
                    <a class="nav-link dropdown hidden-arrow" href="#" id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-bell fa-lg"></i>
                        <span class="badge rounded-pill badge-notification bg-danger">12</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                        <li>
                            <a class="dropdown-item" href="#">Some news</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">Another news</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </li>
                    </ul>
                </li>
            {% endif %}
        </ul>
        <!-- Right elements -->
    </div>
</nav>