post/urls.py
from django.urls import path
from post.views import views
from post.views import jsonview

app_name = 'post'
urlpatterns = [
    path('', views.PostListView.as_view(), name='posts'),
    path('post/<pk>/', views.PostDetailView.as_view(), name='detail'),
    # path('like/', views.LikeView.as_view(), name='like_post'),
    path('create/', views.PostCreate.as_view(), name='create_post'),
    path('create_comment/', views.CommentCreate.as_view(), name='create_comment'),
    path('post/<pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
    path('post/<pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('comment/<pk>/delete/', views.CommentDeleteView.as_view(), name='comm_delete'),
    path('comment/<pk>/update/', views.CommentUpdateView.as_view(), name='comm_update'),
    path('spin', views.Post_json.as_view(), name='post_spin'),
    
    #=========================JSON=====================================
    
    path('comment/<pk>', jsonview.CommentJson.as_view(), name='comment_json'),
    path('post_json', jsonview.post_json, name='post_json'),
    path('post/<pk>/like/', jsonview.LikeView.as_view(), name='like_post'),
]

src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('sessions/', include('user_sessions.urls', namespace='user_sessions')),
    path('user/', include('user.urls', namespace='user')),
    path('', include('post.urls', namespace='post')),
    path('chat/', include('chat.urls', namespace='chat')),

    path('auth/reset_password/', auth_views.PasswordResetView.as_view(
        template_name='user/password_reset_form.html'), name='password_reset'),
    
    path('auth/reset_password_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'), name='password_reset_done'),
    
    path('auth/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html'), name='password_reset_confirm'),
    
    path('auth/reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/password_reset_complete.html'), name='password_reset_complete'),

    path('auth/change_password/', auth_views.PasswordChangeView.as_view(
        template_name='user/change-password.html'), name='password_change'),

    path('user-api/', include('user.api.urls', namespace='user_api')),

    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('auth/register/', views.RegisterView.as_view(), name='register'),
    path('auth/login/', views.LoginView.as_view(), name='login'),
    path('auth/logout/', views.LogoutView.as_view(), name='logout'),

    path('<pk>/', views.UserDetailView.as_view(), name='profile'),
    path('follow/<pk>', views.FollowView.as_view(), name='follow'),
    path('<pk>/update/', views.UserUpdateView.as_view(), name='update'),
    path('<pk>/following/', views.FollowingView.as_view(), name='following'),
]

post/models.py
from django.db import models
import datetime
import os
from django.core.validators import FileExtensionValidator
from uuid import uuid4
from django.shortcuts import reverse
from django.utils.safestring import mark_safe
from user.models import User

def get_post_image(instance, filename):
    upload_to = '{}/{}/{}'.format('user', instance.post.user, 'post')
    ext = filename.split('.')[-1]
    date = instance.post.created_at.strftime('%Y%m%d%H%M%S')
    filename = '{}_{}_{}{}.{}'.format(instance.post.user, 'post', date, uuid4().hex, ext)
    return os.path.join(upload_to, filename)

# Model Manager Feeds
class Post(models.Model):
    user = models.ForeignKey(User, related_name="user_post", on_delete=models.CASCADE)
    caption = models.TextField(max_length=1500, blank=True)
    likes = models.ManyToManyField(User, related_name='post_like', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    # objects: PostManager()

    def __str__(self):
        return f"{self.pk}-{self.user} -- {self.caption[0:20]}"
    
    class Meta:
        ordering = ('-created_at',)

    def save(self, *args, **kwargs):
        self.created_at = datetime.datetime.now()
        super(Post, self).save(*args, **kwargs)

    def likes_no(self):
        return self.likes.count()
    
    def comment_no(self):
        return self.comment_post.count()

    def get_comments(self):
        return self.comment_post.all()[0:1]
        
    def get_absolute_url(self):
        return reverse('post:detail', kwargs={"pk": self.pk})
    
class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_images')
    image = models.ImageField(upload_to=get_post_image, blank=True, null=True, validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])

    def image_tag(self):
        return mark_safe('<img src="/../../media/%s" width="100" height="100" />' % (self.image))

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_user')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comment_post')
    comment = models.CharField(max_length=700)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f"{self.user} commented {self.post} -- {self.comment[0:20]}"

    def save(self, *args, **kwargs):
        self.created_at = datetime.datetime.now()
        super(Comment, self).save(*args, **kwargs)

post/forms.py
from django import forms
from .models import Post, Comment, Image

class PostForm(forms.ModelForm):
    caption = forms.CharField(widget=forms.Textarea(attrs={'rows':4, 'style': 'padding: 10px; resize: none;'}), required=False)
    images = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))
    
    class Meta:
        model = Post
        fields = [
            'caption',
            # 'images',
        ]

class ImageForm(forms.ModelForm):
    image = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))
    
    class Meta:
        model = Image
        fields = [
            'image',
        ]

class CommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={'rows':2, 'style': 'padding: 10px; resize: none; margin-right:9px;'}), required=False)
    
    class Meta:
        model = Comment
        fields = [
            'comment',
        ]

post/views/jsonview.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
import json
from django.core import serializers
from django.http import JsonResponse
from post.forms import ImageForm, PostForm, CommentForm
from post.models import Post, Comment, Image
from user.models import User

def post_json(request):
    qs = Post.objects.all()
    data = serializers.serialize('json', qs)
    return JsonResponse({'data': data})

class CommentJson(LoginRequiredMixin, generic.View):
    model = Comment
    template_name = 'post/detail.html'

    def post(self, request, pk, *args, **kwargs):
        user = User.objects.get(pk=request.user.pk)
        pk = self.kwargs.get("pk")
        posts = Post.objects.get(pk=pk)
        data = json.loads(request.body)
        newcomm = data["comment"]
        comment = Comment.objects.create(user=user, post=posts, comment=newcomm)
        return JsonResponse(comment.comment, safe=False)

class LikeView(LoginRequiredMixin, generic.View):
    login_url = 'user:login'
    redirect_field_name = 'redirect_to'

    def post(self, request, pk):
        data = json.loads(request.body)
        pk_ = data["pk"]
        post = Post.objects.get(pk=pk_)
        checker = None
        
        if request.user in post.likes.all():
            post.likes.remove(request.user)
            checker = 0
        else:
            post.likes.add(request.user)
            checker = 1
        likes = post.likes.count()
        info = {
            "check": checker,
            "num_of_likes": likes
        }
        return JsonResponse(info, safe=False)

post/views/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponseRedirect
import json
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic.edit import FormMixin
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.core import serializers
from itertools import chain
from tomlkit import comment
from post.forms import ImageForm, PostForm, CommentForm
from post.models import Post, Comment, Image
from user.models import User

class Post_json(generic.View):
    template_name = 'post/post_spin.html'
    def get(self, request):
        posts = Post.objects.all()
        context={'posts': posts,}
        return render(request, self.template_name, context)

class PostListView(LoginRequiredMixin, generic.ListView):
    login_url = 'user:login'
    redirect_field_name = 'redirect_to'
    model = Post
    template_name = "post/post.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk_ = self.kwargs.get("pk")
        user = User.objects.get(pk=self.request.user.pk) # get object of logged in user
        following = [prof for prof in user.following.all()] # profile that logged in user is folowing
        posts = []
        qs = None
        #=== following posts===
        for us in following:
            u_post = us.user_post.all()
            posts.append(u_post)
        my_post = self.request.user.user_post.all()
        posts.append(my_post)
        #=== sort and chain post query===
        if len(posts)>0:
            qs = sorted(chain(*posts), reverse=True, key=lambda obj: obj.created_at)
        context['posts'] = qs
        user = self.request.user.pk
        context['users'] = User.objects.get_user_to_follow(pk=user)
        return context 

class PostDetailView(FormMixin, generic.DetailView):
    model = Post
    template_name = "post/detail.html"
    form_class = CommentForm

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse("post:detail", kwargs={"pk": pk})

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        pk_ = self.kwargs.get("pk")
        context['post'] = Post.objects.get(pk=pk_)
        post = Post.objects.get(pk=pk_)
        context['comments'] = Comment.objects.filter(post=post)
        context['form'] = CommentForm()

        context['msg'] = False
    
        if self.request.user.is_authenticated:
            user = self.request.user
            if post.likes.filter(pk=user.pk).exists():
                context['msg'] = True

        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        user = User.objects.get(pk=request.user.pk)
        pk_ = self.kwargs.get("pk")
        post = Post.objects.get(pk=pk_)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = user
            instance.post = post
            instance.save()
            messages.success(request, "Comment Created.")
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(PostDetailView, self).form_valid(form)

class PostCreate(LoginRequiredMixin, generic.View):
    template_name = 'post/create.html'
    login_url = 'user:login'
    redirect_field_name = 'redirect_to'

    def get(self, request):
        form = PostForm()
        return render(request, self.template_name, context={'form':form })

    def post(self, request):
        form = PostForm(request.POST, request.FILES)
        images = request.FILES.getlist("images")
        user = User.objects.get(pk=request.user.pk)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = user
            instance.save()
            for i in images:
                image = Image.objects.create(post=instance, image=i)
                image.save()
            return redirect(user.get_absolute_url())
        else:
            print(form.errors)
        imageform = ImageForm()
        context = {'form': form, 'imageform': imageform}
        return render(request, self.template_name, context)

class CommentCreate(LoginRequiredMixin, generic.View):
    template_name = 'post/detail.html'
    login_url = 'user:login'
    redirect_field_name = 'redirect_to'
        
    def get(self, request):
        form = CommentForm()
        return render(request, self.template_name, context={'form':form })

    def post(self, request):
        form = CommentForm(request.POST)
        user = User.objects.get(pk=request.user.pk)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = user
            instance.post = Post.objects.get(id=request.POST.get('post_comment'))
            instance.save()
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            print(form.errors)
        context = {'form': form}
        return render(request, self.template_name, context)

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Post
    template_name = 'post/delete.html'
    login_url = 'user:login'
    redirect_field_name = 'redirect_to'

    def get_success_url(self) -> str:
        return reverse('post:posts')

    def test_func(self, **kwargs):
        pk_ = self.kwargs.get("pk")
        post = Post.objects.get(pk=pk_)
        return post.user == self.request.user

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Comment
    template_name = 'post/comm_delete.html'
    login_url = 'user:login'
    redirect_field_name = 'redirect_to'

    def get_success_url(self) -> str:
        pk = self.kwargs['pk']
        comment = Comment.objects.get(pk=pk)
        com_pos = comment.post
        return reverse('post:detail', kwargs={"pk": com_pos.pk})

    def test_func(self, **kwargs):
        pk_ = self.kwargs.get("pk")
        comment = Comment.objects.get(pk=pk_)
        return comment.user == self.request.user

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Post    
    form_class = PostForm
    template_name = 'post/update.html'
    login_url = 'user:login'
    redirect_field_name = 'redirect_to'

    def get_success_url(self) -> str:
        pk = self.kwargs['pk']
        return reverse('post:detail', kwargs={"pk": pk})

    def form_valid(self, form):
        user = User.objects.get(pk=self.request.user.pk)
        images = self.request.FILES.getlist("images")
        if form.instance.user == user:
            for i in images:
                image = Image.objects.create(post=form.instance, image=i)
                image.save()
            return super().form_valid(form)
        else:
            form.add_error(None, 'Post not yours')
            return super().form_invalid(form)
    
    def test_func(self, **kwargs):
        pk_ = self.kwargs.get("pk")
        post = Post.objects.get(pk=pk_)
        return post.user == self.request.user

class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Comment    
    form_class = CommentForm
    template_name = 'post/comm_update.html'
    login_url = 'user:login'
    redirect_field_name = 'redirect_to'

    def get_success_url(self) -> str:
        pk = self.kwargs['pk']
        comment = Comment.objects.get(pk=pk)
        com_pos = comment.post
        return reverse('post:detail', kwargs={"pk": com_pos.pk})

    def form_valid(self, form):
        user = User.objects.get(pk=self.request.user.pk)
        if form.instance.user == user:
            return super().form_valid(form)
        else:
            form.add_error(None, 'Comment is  not yours')
            return super().form_invalid(form)
    
    def test_func(self, **kwargs):
        pk_ = self.kwargs.get("pk")
        comment = Comment.objects.get(pk=pk_)
        return comment.user == self.request.user

templates/post/comm_delete.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} - Delete Comment  {% endblock title %}

{% block body %}
<div class="container">
    <div class="row mt-2">
        <div class="col-md-5 col-sm-6">
            <a href="{% url 'post:detail' object.pk %}" class="btn btn-light">Back To Post</a>
        </div>
    </div>

    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-5 col-sm-12 border-bottom">
            <form method="POST">
                {% csrf_token %}
                <h5>Are You Sure?</h5>
                <p>You are about to delete this Comment, this cannot be undone.</p>
                <div class="d-grid gap-2">
                    <button class="btn btn-danger mt-3">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/post/create.html
{% extends 'main/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %} - Create Post {% endblock title %}

{% block body %}
<div class="container">
    <div class="card-header">Create Post</div>
    {{form.errors}}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label class="small mb-1" for="inputCaption">Caption</label>
        {% render_field form.caption class='form-control' %}
        
        <label class="small mb-1" for="inputimages">Image</label><br>
        <input class="form-control" type="file" multiple name="images" accept="image/*" id="id_images">
        
        {% render_field imageform.image class='form-control' %}
        {{imageform.management_form}}
        {% for form in imageform %}
            {{form}}
            <label class="small mb-1" for="inputimages">Image</label><br>
            <input class="form-control" type="file" name="image" accept="image/*" id="id_images">
        {% endfor %}
        
        <div class="modal-footer mt-1">
            <button type="submit" class="btn bottons">Post</button>
        </div>
    </form>
</div>
{% endblock %}

templates/post/detail.html
{% extends "main/base.html" %}
{% load widget_tweaks %}
{% block title %} - Post Feed ({{post.pk}}){% endblock title %}

{% block body %}
<div class="container mt-2">
    <div class="mx-auto" id="{{post.pk}}" style="width: 670px;">
        <div class="p-2 shad">
            <div class="d-flex flex-row justify-content-between align-items-center p-2 border-bottom">
                <div class="d-flex flex-row align-items-center feed-text px-2">
                    <a href="{% url 'user:profile' post.user.pk %}">
                        <img class="rounded-circle" src="{{ post.user.profile_pic.url }}" style="object-fit: cover; width: 50px; height: 50px;">
                    </a>
                    <div class="d-flex flex-column flex-wrap mx-2">
                        <a href="{% url 'user:profile' post.user.pk %}">
                            <span style="font-weight: 600;">{{post.user|capfirst}}</span>
                        </a>
                        <span class="text-black-50 time">{{post.created_at}}</span>
                    </div>
                </div>
                {% if post.user == request.user %}
                    <div class="feed-icon px-2 dropdown">
                        <button class="btn bottons dropdown" type="button" data-bs-toggle="dropdown"  aria-expanded="false" aria-expanded="false">
                            <i class="fa fa-ellipsis-v text-black-50"></i>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="btn dropdown-item" href="{% url 'post:delete' post.pk %}">Delete</a></li>
                            <li><a class="btn dropdown-item" href="{% url 'post:post_update' post.pk %}">Update</a></li>
                        </ul>
                    </div>
                {% endif %}
            </div>
            <div class="p-2 px-3">
                {% if post.caption %}
                    <span class="p-1">{{post.caption}}</span><br>
                {% endif %}
                {% if post.post_images %}
                    <div class="owl-carousel owl-theme">
                        {% for image in post.post_images.all %}
                            <img src="{{ image.image.url }}" class="item" style="object-fit: scale-down; height: 650px;">
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="d-flex justify-content-start p-1 border-top">
                <div class="btn" id="likeBTN">
                    <input type="hidden" id="post_pk" value="{{post.pk}}">
                    {% if request.user not in post.likes.all %}
                        <i class="far fa-heart" style="color: rgb(5, 92, 163);"></i>
                    {% else %}
                        <i class="fa fa-heart" style="color: red;"></i>
                    {% endif %}
                    <span id="like_count">{{post.likes_no}}</span>
                </div>
                <div class="btn">
                    <i class="fas fa-comments mx-1"></i>
                    <span>{{post.comment_no}}</span>
                </div>
            </div>
        </div>
        
        <div class="p-2 shad">
            <div class="card-header d-flex justify-content-center">
            <b>Comments</b>
            </div>
            <div class="card-body p-1">
                {% if comments %}
                    {% for comment in comments %}
                        <div class="shad">
                            <div class="card-header d-flex justify-content-between">
                                <div class="d-flex">
                                    <img class="rounded-circle mx-1" src="{{comment.user.profile_pic.url}}" alt="" style="height: 50px; width: 50px;">
                                    <div class="d-flex flex-column">
                                        <b>{{comment.user|capfirst}}</b>
                                        <div>
                                            {{comment.created_at}}
                                        </div>
                                    </div>
                                </div>

                                {% if comment.user == request.user %}
                                <div class="feed-icon px-2 dropdown ml-auto">
                                    <button class="btn bottons dropdown" type="button" data-bs-toggle="dropdown" aria-expanded="false"
                                        aria-expanded="false">
                                        <i class="fa fa-ellipsis-v text-black-50"></i>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a class="btn dropdown-item" href="{% url 'post:comm_delete' comment.pk %}">Delete</a></li>
                                        <li><a class="btn dropdown-item" href="{% url 'post:comm_update' comment.pk %}">Update</a></li>
                                    </ul>
                                </div>
                                {% endif %}
                            </div>
                            <div class="card-body">
                                {{comment.comment}}
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="d-flex justify-content-center align-items-center">
                        <h4>Be the first to comment.</h4>
                    </div>
                {% endif %}
            </div>
        </div>
        
        <div class="p-2 shad">
            <form action="{% url 'post:create_comment' %}" method="POST" id="comment_form">
                {% csrf_token %}
                <input type="hidden" name="post_comment" value="{{post.pk}}">
                <div class="d-flex justify-content-center">
                    {% render_field form.comment class='form-control' placeholder='Make a Comment.' %}
                    <button type="submit" class="btn bottons"><i class="fas fa-location-arrow"></i></button>
                </div>
            </form>
        </div>    
    </div>
</div>
{% endblock %}

templates/post/post.html
{% extends "main/base.html" %}
{% load static %}
{% block title %} - Post Feed{% endblock title %}
<script type="text/javascript" src="{% static 'main/post.js' %}"></script>


{% block body %}
<div class="container mt-4 mb-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-8 infinite-container">
            {% for post in posts %}
                <div class="feed shad infinite-item rounded" id="{{post.pk}}">
                    <div class="card-header px-2">
                        <div class="d-flex flex-row justify-content-between align-items-center">
                            <div class="d-flex flex-row align-items-center feed-text px-2">
                                <a href="{% url 'user:profile' post.user.pk %}">
                                    <img class="rounded-circle" src="{{ post.user.profile_pic.url }}" style="object-fit: cover; width: 50px; height: 50px;">
                                </a>
                                <div class="d-flex flex-column flex-wrap mx-2">
                                    <a href="{% url 'user:profile' post.user.pk %}">
                                        <span style="font-weight: 600;">{{post.user|capfirst}}</span>
                                    </a>
                                    <p class="tx-11 text-muted m-0">{{post.created_at}}</p>
                                </div>
                            </div>
                            {% if post.user == request.user %}
                                <div class="feed-icon px-2 dropdown">
                                    <button class="btn bottons dropdown" type="button" data-bs-toggle="dropdown"  aria-expanded="false" aria-expanded="false">
                                        <i class="fa fa-ellipsis-v text-black-50"></i>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a class="btn dropdown-item" href="{% url 'post:delete' post.pk %}">Delete</a></li>
                                        <li><a class="btn dropdown-item" href="{% url 'post:post_update' post.pk %}">Update</a></li>
                                    </ul>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="p-2 px-3">
                        <a href="{% url 'post:detail' post.pk %}">
                            {% if post.caption %}
                                <span>{{post.caption}}</span><br>
                            {% endif %}
                            {% if post.post_images %}
                                <div class="row owl-carousel owl-theme">
                                    {% for image in post.post_images.all %}
                                            <img src="{{ image.image.url }}" class="item" style="object-fit: cover; height: 500px;">
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </a>
                    </div>
                    <div class="d-flex justify-content-start p-1 border-top">
                        <div class="btn" id="likeBTN">
                            <input type="hidden" id="post_pk" value="{{post.pk}}">
                            {% if request.user not in post.likes.all %}
                                <i class="far fa-heart" style="color: rgb(5, 92, 163);"></i>
                            {% else %}
                                <i class="fa fa-heart" style="color: red;"></i>
                            {% endif %}
                            <span id="like_count">{{post.likes_no}}</span>
                        </div>
                        <a class="btn" href="{% url 'post:detail' post.pk %}">
                            <i class="fas fa-comments mx-1"></i><span>{{post.comment_no}}</span>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
         <div class="col-md-4 following">
            <div class="shad" style="padding: 15px 13px;">
                {% for following in request.user.get_following %}
                    <ol class="py-1 my-1 border-bottom" style="padding-left: 0;">
                        <a href="{% url 'user:profile' following.pk %}">
                            <img class="rounded-circle mx-1" src="{{ following.profile_pic.url }}" style="object-fit: cover; width: 50px; height: 50px;">
                            <b>{{following|capfirst}}</b>
                        </a>
                    </ol>
                {% endfor %}
            </div>

            <div class="card rounded">
                <div class="card-body">
                    <div class="d-flex justify-content-center mb-2">
                        <h6 class="card-title border-bottom p-2"><b>People you may know</b></h6>
                    </div>
                    {% for prof in users %}
                        <div class="d-flex justify-content-between mb-2 pb-2 border-bottom">
                            <div class="d-flex align-items-center hover-pointer">
                                <a href="{% url 'user:profile' prof.pk %}">
                                    <img class="img-xs rounded-circle" src="{{ prof.profile_pic.url }}" alt="">
                                </a>
                                <div class="mx-2">
                                    <a href="{% url 'user:profile' prof.pk %}">
                                        <p class="mb-1">{{prof|capfirst}}</p>
                                    </a>
                                    <p class="tx-11 text-muted mb-1">{{mutualfriends_num}} Mutual Friends</p>
                                </div>
                            </div>
                            <form action="{% url 'user:follow' request.user.pk %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="prof_pk" value="{{ prof.pk }}">
                                <button id="follow" class="btn bottons" type="submit" style="margin-left: 15px;">Follow</button>
                            </form>
                        </div>
                    {% endfor %}
                </div>
            </div>
         </div>
    </div>
</div>
{% endblock %}