chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.ChatView.as_view(), name='chat_index'),
    path('<pk>', views.ChatDirectView.as_view(), name='chat_direct'),
    path('send/<pk>/', views.SendChat.as_view(), name='send_chat'),
    path('receive/<pk>/', views.ReceiveChat.as_view(), name='receive_chat'),
    path('notification/', views.ChatNotif.as_view(), name='notif_chat'),
]

post/urls.py
from django.urls import path
from post.views import views
from post.views import jsonview

app_name = 'post'
urlpatterns = [
    path('', views.PostListView.as_view(), name='posts'),
    path('post/<pk>/', views.PostDetailView.as_view(), name='detail'),
    # path('like/', views.LikeView.as_view(), name='like_post'),
    path('create/', views.PostCreate.as_view(), name='create_post'),
    path('create_comment/', views.CommentCreate.as_view(), name='create_comment'),
    path('post/<pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
    path('post/<pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('comment/<pk>/delete/', views.CommentDeleteView.as_view(), name='comm_delete'),
    path('comment/<pk>/update/', views.CommentUpdateView.as_view(), name='comm_update'),
    path('spin', views.Post_json.as_view(), name='post_spin'),
    
    #=========================JSON=====================================
    
    path('comment/<pk>', jsonview.CommentJson.as_view(), name='comment_json'),
    path('post_json', jsonview.post_json, name='post_json'),
    path('post/<pk>/like/', jsonview.LikeView.as_view(), name='like_post'),
]

src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('sessions/', include('user_sessions.urls', namespace='user_sessions')),
    path('user/', include('user.urls', namespace='user')),
    path('', include('post.urls', namespace='post')),
    path('chat/', include('chat.urls', namespace='chat')),

    path('auth/reset_password/', auth_views.PasswordResetView.as_view(
        template_name='user/password_reset_form.html'), name='password_reset'),
    
    path('auth/reset_password_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'), name='password_reset_done'),
    
    path('auth/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html'), name='password_reset_confirm'),
    
    path('auth/reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/password_reset_complete.html'), name='password_reset_complete'),

    path('auth/change_password/', auth_views.PasswordChangeView.as_view(
        template_name='user/change-password.html'), name='password_change'),

    path('user-api/', include('user.api.urls', namespace='user_api')),

    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/api/urls.py
from django.urls import path
from . import views

app_name = 'user_api'
urlpatterns = [
    path('<pk>', views.UserDetail.as_view(), name='users'),
    path('user/create/', views.RegistrationApiView.as_view(), name='create_user'),
    path('user/<pk>/update/', views.UpdateUserView.as_view(), name='update_user'),

]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('auth/register/', views.RegisterView.as_view(), name='register'),
    path('auth/login/', views.LoginView.as_view(), name='login'),
    path('auth/logout/', views.LogoutView.as_view(), name='logout'),

    path('<pk>/', views.UserDetailView.as_view(), name='profile'),
    path('follow/<pk>', views.FollowView.as_view(), name='follow'),
    path('<pk>/update/', views.UserUpdateView.as_view(), name='update'),
    path('<pk>/following/', views.FollowingView.as_view(), name='following'),
]

user/models.py
from django.db import models
import os
from django.core.validators import FileExtensionValidator
from uuid import uuid4
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.shortcuts import reverse

class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None):    
        """
        Creates and saves a User with the given email, username and password.
        """
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have an username')
        user = self.model(
            email = self.normalize_email(email),
            username=username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        """
        Creates and saves a superuser with the given email, username and password.
        """
        user = self.create_user(
            email = self.normalize_email(email), 
            username=username, 
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

    def get_user_to_follow(self, pk):
        users = User.objects.all().exclude(pk=pk)
        my_user = User.objects.get(pk=pk)
        avail = [user for user in users if user not in my_user.get_following()]
        return avail
    
def get_profile_image(instance, filename):
    upload_to = '{}/{}/{}'.format('user', instance.pk, 'profile')
    ext = filename.split('.')[-1]
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        filename = '{}_{}.{}'.format(instance.pk, uuid4().hex, ext)
    return os.path.join(upload_to, filename)

def get_default_profile_image():
    return "user/default/profile.jpg"

def get_cover_image(instance, filename):
    upload_to = '{}/{}/{}'.format('user', instance.pk, 'cover')
    ext = filename.split('.')[-1]
    if instance.pk:
        filename = '{}_{}.{}'.format(instance.pk, 'cover', ext)
    else:
        filename = '{}_{}.{}'.format(instance.pk, uuid4().hex, ext)
    return os.path.join(upload_to, filename)

def get_default_cover_image():
    return "user/default/cover.jpg"

class User(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address', max_length=40, unique=True)
    username = models.CharField(max_length=30, primary_key=True, unique=True, verbose_name='username')
    follower = models.ManyToManyField("User", blank=True, related_name='followers') # people following profile
    following = models.ManyToManyField("User", blank=True, related_name='followings') # people profile is following 
    cover_pic = models.ImageField(upload_to=get_cover_image, default=get_default_cover_image, blank=True, null=True, validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])
    profile_pic = models.ImageField(upload_to=get_profile_image, default=get_default_profile_image, blank=True, null=True, validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])

    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    hide_email = models.BooleanField(default=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return f"{self.username}"

    def get_absolute_url(self):
        return reverse('user:profile', kwargs={"pk": self.pk})

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin

    def get_all_permissions(user=None):
        if user.is_admin:
            return set()

    def get_follower(self):
        return self.follower.all()

    def get_follower_no(self):
        return self.follower.count()

    def get_following(self):
        return self.following.all()

    def get_followering_no(self):
        return self.following.count()

post/forms.py
from django import forms
from .models import Post, Comment, Image

class PostForm(forms.ModelForm):
    caption = forms.CharField(widget=forms.Textarea(attrs={'rows':4, 'style': 'padding: 10px; resize: none;'}), required=False)
    images = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))
    
    class Meta:
        model = Post
        fields = [
            'caption',
            # 'images',
        ]

class ImageForm(forms.ModelForm):
    image = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))
    
    class Meta:
        model = Image
        fields = [
            'image',
        ]

class CommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={'rows':2, 'style': 'padding: 10px; resize: none; margin-right:9px;'}), required=False)
    
    class Meta:
        model = Comment
        fields = [
            'comment',
        ]

user/api/views.py
from user.models import User
from django.shortcuts import get_object_or_404
from rest_framework import generics, permissions
from rest_framework.exceptions import PermissionDenied
from django.http import Http404
from user.api import serializers
from .permissions import IsUserWriteOnly
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.pagination import PageNumberPagination

class UserDetail(APIView):
    """User Detail"""
    serializer_class = serializers.UserSerializer
    # pagination_class = PageNumberPagination

    def get(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        serializer = serializers.UserSerializer(user)
        return Response(serializer.data)

    def delete(self, request, pk, *args, **kwargs):
        user = User.objects.get(pk=self.kwargs["pk"])
        if not request.user == user:
            raise PermissionDenied("You can not delete this user. You must be the Owner")
        return super().delete(request, *args, **kwargs)

    def put(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        serializer = serializers.UserSerializer(user, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class RegistrationApiView(generics.CreateAPIView):
    permission_classes = ()
    authentication_classes = ()
    serializer_class = serializers.UserCreateSerializer

class UpdateUserView(APIView):
    permission_classes = [IsUserWriteOnly] # Custom permission class used
    serializer_class = serializers.UpdateUserSerializer

    def get(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        serializer = serializers.UpdateUserSerializer(user)
        return Response(serializer.data)

    def put(self, request, pk, *args, **kwargs):
        user = self.get_object(pk)
        serializer = serializers.UpdateUserSerializer(user, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from .forms import CreateUserForm, UserUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from post.forms import PostForm
from django.contrib import messages
from django.views.generic.edit import FormMixin
from .models import User
from django.http import JsonResponse
from post.models import Post, Image, Comment

class RegisterView(generic.View):
    template_name = 'user/register.html'

    def get(self, request):
        message = ''
        form = CreateUserForm()
        return render(request, self.template_name, context={'message': message, 'form':form })

    def post(self, request):
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = authenticate(request, email=email, password=password)
            
            if user is not None:
                login(request, user)
                return redirect(request.user.get_absolute_url())

        context = {'form':form,}
        return render(request, self.template_name, context)

class LoginView(generic.View):
    template_name = 'user/login.html'
    redirect_authenticated_user=True
    
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('post:posts')
            pass
        return render(request, self.template_name)
        
    def post(self, request):
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email = email, password = password)
        if user is not None:
            login(request, user)
            return redirect('post:posts')
        else:
            messages.info(request, 'Username or Password Incorrect.')
        return render(request, self.template_name)

class LogoutView(generic.View):
    def get(self, request):
        logout(request)
        return redirect('user:login')

class UserDetailView(FormMixin, generic.DetailView):
    model = User
    template_name = "user/timeline.html"
    context_object_name = 'profiles'
    form_class = PostForm

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse("user:profile", kwargs={"pk": pk})
    
    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        pk_ = self.kwargs.get("pk")
        pk = User.objects.get(pk=pk_)
        context['posts'] = Post.objects.filter(user=pk)
        context['form'] = PostForm()
        user = self.request.user.pk
        context['photos'] = Image.objects.filter(post__user=pk).order_by('post')
        context['users'] = User.objects.get_user_to_follow(pk=user)
        
        users = User.objects.get_user_to_follow(pk=user)
        for user in users:
            other_follow = user.get_following()
            user_follow = self.request.user.get_following()
            friends = []
            for f1 in user_follow:
                for f2 in other_follow:
                    if f1 == f2:
                        mut_user = f1
                        friends.append(mut_user)
        return context

    def post(self, request):
        form = PostForm(request.POST, request.FILES)
        images = request.FILES.getlist("images")
        user = User.objects.get(pk=request.user.pk)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = user
            instance.save()
            for i in images:
                image = Image.objects.create(post=instance, image=i)
            messages.success(request, "Post Created")
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(UserDetailView, self).form_valid(form)

class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = "user/update.html"
    login_url = 'user:login'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse("user:profile", kwargs={"pk": pk})

    def form_valid(self, form):
        if form.instance.pk == self.request.user.pk:
            form.instance.username = self.request.user.username
            return super().form_valid(form)
        else:
            form.add_error(None, 'Post not yours')
            return super().form_valid(form)

    def test_func(self, **kwargs):
        pk_ = self.kwargs.get("pk")
        user = User.objects.get(pk=pk_)
        return user == self.request.user

class FollowView(LoginRequiredMixin, generic.View):
    login_url = 'user:login'
    redirect_field_name = 'redirect_to' 

    def post(self, request, pk):
        my_profile = User.objects.get(pk=request.user.pk)
        # other profiles
        pk = request.POST.get('prof_pk')
        profile = get_object_or_404(User, pk=pk)

        if my_profile == profile:
            messages.info("You can't follow yourself")
        else:
            if profile in my_profile.following.all():
                my_profile.following.remove(profile)
                profile.follower.remove(my_profile)
            else:
                my_profile.following.add(profile)
                profile.follower.add(my_profile)
            return redirect(request.META.get('HTTP_REFERER'))

class FollowingView(LoginRequiredMixin, generic.View):
    login_url = 'user:login'
    redirect_field_name = 'redirect_to'
    template_name = "user/following.html"

    def get(self, request, pk):
        profile = User.objects.get(pk=request.user.pk)
        following = profile.get_following()

        context = {'following': following}
        return render(request, self.template_name, context)

templates/user/following.html
{% extends 'user/profile.html' %}

{% block following %}
    {{following}}

{% endblock following %}

templates/user/login.html
{% extends "main/base.html" %}
{% block title %} - Login {% endblock title %}

{% block body %}
<div class="container login-body">
    <div class="p-4 border">
        <div class="mb-5">
            <h3 class="h4 font-weight-bold text-theme">Login</h3>
        </div>
        {% if messages %}
            {% for message in messages %}
                <p class="text-muted text-center mt-1 mb-1" style="color: red!important;">{{message}}</p>
            {% endfor %}
        {% endif %}
        <form action="{% url 'user:login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group mb-2">
                <label for="exampleInputEmail" class="mb-0">Email Address</label>
                <input type="email" name="email" id="email" placeholder="Email" class="form-control">
            </div>
            <div class="form-group mb-4">
                <label for="exampleInputPassword" class="mb-0">Password</label>
                <input type="password" name="password" id="password" placeholder="Password" class="form-control">
                <i class="fas fa-eye pwshow" id="togglePassword"></i>
            </div>
            <div class="row mb-4">
                <div class="col d-flex justify-content-start">
                    <button type="submit" class="btn bottons">Login</button>
                </div>
                <div class="col d-flex justify-content-end">
                    <a href="{% url 'password_reset' %}" class="forgot-link text-primary">Forgot password?</a>
                </div>
            </div>
        </form>

        <p class="text-muted text-center mt-1 mb-0">
            Don't have an account? <a href="{% url 'user:register' %}" class="text-primary ml-1">Register</a>
        </p>
    </div>
</div>
{% endblock %}

templates/user/password_reset_complete.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} - Password reset complete {% endblock title %}

{% block body %}
<div class="login-body" style="top: 35%;">
    <h1>Password reset complete</h1>
    <p>Your new password has been set. You can log in now on the <a href="{% url 'user:login'%}" style="text-decoration: underline !important;">log in</a> page.</p>
</div>
{% endblock %}

templates/user/password_reset_done.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} Email Sent{% endblock title %}

{% block body %}
    <div class="container login-body" style="top: 35%;">
        <h1>Check your inbox.</h1>
        <p>We've emailed you instructions for setting your password. You should receive the email shortly!</p>
    </div>
{% endblock %}

templates/user/profile.html
{% extends 'main/base.html' %}
{% load widget_tweaks %}
{% load static %}
<script type="text/javascript" src="{% static 'main/user.js' %}"></script>

{% block body %}
<div class="container-fluid">
    <div class="profile-page tx-13">
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="profile-header">
                    <div class="cover">
                        <div class="gray-shade"></div>
                        <figure>
                            <img src="{{ profiles.cover_pic.url }}" class="img-fluid" alt="profile cover" style="height: 300px;">
                        </figure>
                        <div class="cover-body d-flex justify-content-between align-items-center">
                            <div>
                                <img class="profile-pic" src="{{ profiles.profile_pic.url }}"
                                    alt="profile">
                                <span class="profile-name">{{ profiles.username|capfirst }}</span>
                            </div>
                            <div class="d-none d-md-block">
                                {% if profiles == request.user %}
                                    <button type="button" class="btn bottons btn-icon-text" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                        Post
                                    </button>
                                    <a class="btn edit-bottons btn-icon-text btn-edit-profile" href="{% url 'user:update' profiles %}">
                                        <i class="far fa-edit"></i> Edit profile
                                    </a>
                                {% else %}
                                    <a href="{% url 'chat:chat_direct' profiles.pk %}" class="btn btn-primary">Send Message</a>
                                    <form action="{% url 'user:follow' profiles.pk %}" method="POST" class="btn" id="follow_form">
                                        {% csrf_token %}
                                        <input type="hidden" name="prof_pk" value="{{ profiles.pk }}">
                                        {% if profiles in request.user.following.all %}
                                            <button id="unfollow" class="btn btn-danger" type="submit">Unfollow</button>
                                        {% else %}
                                            <button id="follow" class="btn btn-primary" type="submit">Follow</button>
                                        {% endif %}
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Create a post</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <form action="" method="POST" enctype="multipart/form-data">
                                    <div class="modal-body">
                                        {% csrf_token %}
                                        <label class="small mb-1" for="inputCaption">Caption</label>
                                        {% render_field form.caption class='form-control' %}
                                        
                                        <label class="small mb-1" for="inputimages">Image</label><br>
                                        <input class="form-control" type="file" multiple name="images" accept="image/*" id="id_images">
                                        
                                        {% render_field imageform.image class='form-control' %}
                                        {{imageform.management_form}}
                                        {% for form in imageform %}
                                            {{form}}
                                            <label class="small mb-1" for="inputimages">Image</label><br>
                                            <input class="form-control" type="file" name="images" accept="image/*" id="id_images">
                                        {% endfor %}
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <button type="submit" class="btn bottons">Post</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="header-links">
                        <ul class="links d-flex align-items-center mt-3 mt-md-0">
                            <li class="header-link-item d-flex align-items-center active">
                                <i class="fas fa-photo-video"></i>
                                <a class="pt-1px d-none d-md-block" href="{% url 'user:profile' profiles.pk %}"> Timeline</a>
                            </li>
                            <li class="header-link-item ms-2 border-left d-flex align-items-center">
                                <i class="fas fa-users"></i>
                                <a class="pt-1px d-none d-md-block" href="{% url 'user:following' profiles.pk %}">Following 
                                    <span class="text-muted tx-12">{{profiles.get_followering_no}}</span>
                                </a>
                            </li>
                            <li class="header-link-item ms-2 border-left d-flex align-items-center">
                                <i class="fas fa-users"></i>
                                <a class="pt-1px d-none d-md-block" href="#">Followers
                                    <span class="text-muted tx-12">{{profiles.get_follower_no}}</span>
                                </a>
                            </li>
                            <li class="header-link-item ms-2 border-left d-flex align-items-center">
                                <i class="far fa-image"></i>
                                <a class="pt-1px d-none d-md-block" href="#">Photos</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        {% block timeline %}
        
        {% endblock timeline %}
        {% block following %}
        
        {% endblock following %}
    </div>
</div>
{% endblock body %}

templates/user/update.html
{% extends 'main/base.html' %}
{% load widget_tweaks %}

{% block body %}
<div class="container-fluid">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="row">    
            <div class="col-xl-4">
                <!-- Profile picture card-->
                <div class="card mb-4 mb-2">
                    <div class="card-header">Profile Picture</div>
                    <div class="card-body text-center">
                        <!-- Profile picture image-->
                        <img class="img-account-profile rounded-circle mb-2" src="{{user.profile_pic.url}}" alt="">
                        <!-- Profile picture upload button-->
                        <input type="file" name="profile_pic" accept="image/*" id="id_profile_pic">
                    </div>
                </div>
                <div>
                    <a href="{% url 'password_change' %}" class="btn bottons">Change Password</a>
                </div>
            </div>
            <div class="col-xl-8">
                <!-- Account details card-->
                <div class="card mb-4">
                    <div class="card-header">Account Details</div>
                    <div class="card-body">
                        <!-- Form Group (username)-->
                        <div class="mb-3">
                            {{form.username.errors}}
                            <label class="small mb-1" for="inputUsername">Username</label>
                            <!-- <input class="form-control" id="{{form.username.id_for_label}}" type="text" placeholder="Enter your username" value="{{form.username.value}}" required='false'> -->
                            {% render_field form.username|attr:"readonly:True" class='form-control-plaintext' %}
                            <!-- <small style="color: red;">{{ form.username.help_text }}</small> -->
                        </div>
                        <!-- Form Group (email address)-->
                        <div class="mb-3">
                            {{form.errors}}
                            <label class="small mb-1" for="inputEmailAddress">Email address</label>
                            <!-- <input class="form-control" id="{{form.email.id_for_label}}" type="email" placeholder="Enter your email address" value="{{form.email.value}}" required> -->
                            {% render_field form.email class='form-control' %}

                        </div>
                        <div class="mb-3">
                            <label class="small mb-1" for="inputCoverPicture">Cover Picture</label><br>
                            <img class="img-account-profile small mb-2" src="{{user.cover_pic.url}}" alt="">
                            <input class="form-control" type="file" name="cover_pic" accept="image/*" id="id_cover_pic" title="">
                        </div>
                        <div class="modal-footer mt-1" style="border-top: 0 solid #dee2e6">
                            <!-- Save changes button-->
                            <button class="btn bottons" type="submit">Save changes</button>
                            <button type="button" id="submit" name="submit" class="btn btn-secondary" value="Previous Page" onClick="javascript:history.go(-1);">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}